### PR TITLE
Update log

### PR DESCRIPTION
**Pull request by tacaswell**

### CODE REVIEW

**Comment by shroffk** [comment]
@berryma4 can you help with this merge

**Comment by shroffk** [comment]
P.S. @arkilic 
I have also added another argument for defining timeout

**Comment by ghost** [comment]
@shroffk great, i wonder what other useful stuff you don't expose to the user that you've implemented on the server side

**Comment by shroffk** [comment]
This was my first python project so I am cleaning up and adding new feature as and when time permits.

**Comment by ghost** [comment]
👍

**Comment by danielballan** [comment]
@shroffk Would you be willing to do the rebase on this, since you are more familiar with the codebase than any of us?

**Comment by shroffk** [comment]
Ok, I will..

**Comment by danielballan** [comment]
@shroffk I keep getting requests for this functionality. Any chance you can make time to rebase this soon?

**Comment by danielballan** [comment]
cc @Brudhu

**Comment by shroffk** [comment]
The requested changes have been merged into the main pyolog library
https://github.com/Olog/pyOlog/pull/7

regarding getting them into the NSLSII version, I looked at the pull request and the changes are quite numerous...Is there a way for me to get some input of what all the NSLSII changes incorporate.

**Comment by shroffk** [comment]
I do not have permission to accept this pull request, @danielballan would you be willing to resolve this with me.

**Comment by danielballan** [comment]
Yes, I'm not really familiar with either codebase (NSLS-II fork or upstream) but I'm wiling to help dig through this. Come find me today or tomorrow if you are around. (Office 150 now.)

**Comment by tacaswell** [comment]
Replaced by https://github.com/NSLS-II/pyOlog/pull/5 which just re-wrote the required functionality.

**Pull request closed without merging**
