### PR TITLE
ENH:Attempt to add timeout to get, put, post

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
@danielballan give this a shot

**Comment by danielballan** [comment]
That looks good. I took a quick look at the docs for `request` and read, [in this section](http://docs.python-requests.org/en/master/user/advanced/#timeouts), "it is good practice to set your timeout to slightly larger than a multiple of 3 [seconds], which is the default TCP transmission window." Would 3.5 be a better default value than 2?

**Comment by ghost** [comment]
@tacaswell and I picked 2, we were off by a second and a half :). I think even 4.5 wouldn't hurt given olog also authenticates. I will test it and make the corresponding changes to the PR

**Comment by ghost** [comment]
attn @danielballan

**Comment by danielballan** [comment]
Attn @cmazzoli This should solve the issue with the Olog subscription hanging scans. If the Olog does not respond after ~4 seconds, an error will be raised in Python. The RunEngine will catch that error, print a warning, and continue with the scan.

**Comment by danielballan** [comment]
attn @arkilic By coincidence, when I visited CSX to install the updated pyolog, the Olog happened to be down (_what are the odds?!_) and so I had the opportunity to test that, with this upgrade, bluesky is able to run the scan after a ~5 second delay, showing a warning about a ReadTImeoutError.

**Comment by ghost** [comment]
Mission accomplished with a 27 character commit  👍

**Pull request merged**
